### ISSUE TITLE
Should we put the docstrings into the C sources?

### ISSUE THREAD

**Issue by torfsen** [rshk/pygpgme#1]
You [wrote on LaunchPad](https://bugs.launchpad.net/pygpgme/+bug/530634/comments/3) that you didn't get Sphinx' autodoc extraction of docstring from the C source to work. I just managed to do that and was wondering if moving the docstrings into the C sources would be a good idea.

To get this to work you need to have the fully built `gpgme` module available when running Sphinx. Assuming that you're working in a virtualenv, you can do

```
(venv) pygpgme $ ./setup.py bdist  # Build module with updated docstring from C sources
(venv) pygpgme $ pip install -e .  # Install pygpgme as an editable dependency
(venv) pygpgme $ cd docs
(venv) pygpgme/docs $ rm -rf _build
(venv) pygpgme/docs $ make html
```

That way, the usual autodoc constructs like `.. autoclass:: gpgme.Context` will work.

The advantages of this approach would be that the docstrings are kept close to the actual function/class definitions and that the docstrings are available in Python via `help` and `__doc__`. However, putting the docstrings into the C source means that updating the Sphinx documentation requires a build of the package, which in turn requires `libgpgme` to be installed. The latter is probably not the case on Read the Docs.

Personally, I'm in favour of moving the docstrings into the C sources, provided we can get Read the Docs to work or find another suitable way of automatically building and hosting the documentation.

What do you think? If you are interested I'd be happy to provide a pull request with the necessary changes to move the docstrings into the C sources.

**Comment by rshk** [comment]
I think the main problem here was with RTD not being able to build C extensions.. an alternative might be to build locally / upload somewhere, but that means losing quite a lot of advantages of using RTD..

**Comment by torfsen** [comment]
Losing RTD seems like a deal-breaker to me, too. I'm therefore closing this issue. If someone comes up with a suitable replacement for RTD we can re-evaluate.
