### ISSUE TITLE
trying to install or build this, an error appears => missing gpgme.h

### ISSUE THREAD

**Issue by tephyrnex** [rshk/pygpgme#6]
In fact, looking at the src folder, I can not find a gmgme.h

**Comment by kevinl95** [comment]
Make sure that you have the GPGME library installed. I received this error and installed it on my Mac as follows:

`brew install gpgme`

**Comment by rshk** [comment]
As @kevinl95 said, the actual library is not shipped with pygpgme. Make sure you have it installed, along with the required header files (usually this will be a `-dev` package on debian-like linux distros).
